- set_fact:
    server_arch: >-
      {%- if ansible_architecture in ["armv7l", "armhf", "aarch32"] -%}
      armhf
      {%- elif ansible_architecture in ["armv8l", "aarch64"] -%}
      arm64
      {%- elif ansible_architecture == "x86_64" -%}
      amd64
      {%- endif -%}
  tags: always

- set_fact:
    certbot_tag: "{{ certbot_tag_arch_map[server_arch] }}"
  tags: always

- import_tasks: deps.yml
  tags:
    - nginx_deps

- import_tasks: nginx.yml
  tags:
    - nginx_config

- import_tasks: vhosts.yml
  tags:
    - vhosts_config

- import_tasks: certbot.yml
  tags:
    - certbot_install
