- name: copy vhost file for nginx
  template:
    src: "{{ item.src }}"
    dest: "{{ nginx_config_dir | default('/etc/nginx/conf.d') }}/{{ item.dest | default(item.src) | basename | regex_replace('\\.j2$') }}"
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d {{ item.dest | default(item.src) | basename | regex_replace('\\.j2$') }}"
    mode: 0644
  with_items: "{{ nginx_vhost_files }}"
  notify:
    - reload nginx


#- name: copy hornet nginx config
#  template:
#    src: ../shared-files/hornet.conf.j2
#    dest: /etc/nginx/conf.d/hornet.conf
#    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d hornet.conf"
#  notify:
#    - reload nginx

#- name: copy grafana nginx config
#  template:
#    src: ../shared-files/grafana.conf.j2
#    dest: /etc/nginx/conf.d/grafana.conf
#    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d grafana.conf"
#  notify:
#    - reload nginx
#
#- name: copy prometheus nginx config
#  template:
#    src: ../shared-files/prometheus.conf.j2
#    dest: /etc/nginx/conf.d/prometheus.conf
#    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d prometheus.conf"
#  notify:
#    - reload nginx
#
#- name: copy alertmanager nginx config
#  template:
#    src: ../shared-files/alertmanager.conf.j2
#    dest: /etc/nginx/conf.d/alertmanager.conf
#    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d alertmanager.conf"
#  notify:
#    - reload nginx
#
#- name: copy tanglemonitor nginx config
#  template:
#    src: ../shared-files/tanglemonitor.conf.j2
#    dest: /etc/nginx/conf.d/tanglemonitor.conf
#    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d tanglemonitor.conf"
#  notify:
#    - reload nginx
