- name: copy vhost file for nginx
  template:
    src: "{{ item.src }}"
    dest: "{{ nginx_config_dir | default('/etc/nginx/conf.d') }}/{{ item.dest | default(item.src) | basename | regex_replace('\\.j2$') }}"
    validate: "/usr/local/bin/validate_nginx_config.sh -t %s -d {{ item.dest | default(item.src) | basename | regex_replace('\\.j2$') }}"
    mode: 0644
  with_items: "{{ nginx_vhost_files }}"
  notify:
    - reload nginx
